# Generated by Django 3.2 on 2023-01-19 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20230118_0425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='car_photo1',
            new_name='car_photo_1',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='car_photo2',
            new_name='car_photo_2',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='car_photo3',
            new_name='car_photo_3',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='car_photo4',
            new_name='car_photo_4',
        ),
    ]
